name = "SparseLNNS"
uuid = "5f866e5d-c780-4b8c-babf-162a06d3e5e3"
authors = ["angeris <guille@angeris.net>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
