name = "CADSketchUI"
uuid = "29c9e627-0ef8-437b-af8d-1571606d7931"
authors = ["angeris <guille@angeris.net>"]
version = "0.1.0"

[deps]
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"

[compat]
CImGui = "7.0.0"
GLFW = "3.4.6"
ModernGL = "1.1.8"
