name = "CADConstraints"
uuid = "8e806ec7-fa68-4964-83a1-12fcd9f6efd6"
authors = ["angeris <guille@angeris.net>"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseLNNS = "5f866e5d-c780-4b8c-babf-162a06d3e5e3"

[compat]
SparseArrays = "1.11.0"
SparseLNNS = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
